name: Regression

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 5 * * 6"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux_os:
    name: ${{ matrix.os }} (${{ matrix.browser }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        browser: [chrome]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install dependencies
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo apt-get -qq update
          sudo apt-get -qq upgrade
          sudo apt-get -yq autoremove
          npm ci

      - name: Run WebdriverIO tests
        run: npm run wdio
